require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/grouped_payments', type: :request do
  # GroupedPayment. As you add validations to GroupedPayment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      GroupedPayment.create! valid_attributes
      get grouped_payments_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      grouped_payment = GroupedPayment.create! valid_attributes
      get grouped_payment_url(grouped_payment)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_grouped_payment_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'render a successful response' do
      grouped_payment = GroupedPayment.create! valid_attributes
      get edit_grouped_payment_url(grouped_payment)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new GroupedPayment' do
        expect do
          post grouped_payments_url, params: { grouped_payment: valid_attributes }
        end.to change(GroupedPayment, :count).by(1)
      end

      it 'redirects to the created grouped_payment' do
        post grouped_payments_url, params: { grouped_payment: valid_attributes }
        expect(response).to redirect_to(grouped_payment_url(GroupedPayment.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new GroupedPayment' do
        expect do
          post grouped_payments_url, params: { grouped_payment: invalid_attributes }
        end.to change(GroupedPayment, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post grouped_payments_url, params: { grouped_payment: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested grouped_payment' do
        grouped_payment = GroupedPayment.create! valid_attributes
        patch grouped_payment_url(grouped_payment), params: { grouped_payment: new_attributes }
        grouped_payment.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the grouped_payment' do
        grouped_payment = GroupedPayment.create! valid_attributes
        patch grouped_payment_url(grouped_payment), params: { grouped_payment: new_attributes }
        grouped_payment.reload
        expect(response).to redirect_to(grouped_payment_url(grouped_payment))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        grouped_payment = GroupedPayment.create! valid_attributes
        patch grouped_payment_url(grouped_payment), params: { grouped_payment: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested grouped_payment' do
      grouped_payment = GroupedPayment.create! valid_attributes
      expect do
        delete grouped_payment_url(grouped_payment)
      end.to change(GroupedPayment, :count).by(-1)
    end

    it 'redirects to the grouped_payments list' do
      grouped_payment = GroupedPayment.create! valid_attributes
      delete grouped_payment_url(grouped_payment)
      expect(response).to redirect_to(grouped_payments_url)
    end
  end
end
